os: linux
dist: xenial

before_install: 
    - sudo apt-get update -qq
    - sudo apt-get upgrade -qq
    - sudo apt-get install -y build-essential 
    - sudo apt-get install -y gperf
    - sudo apt-get install -y python3 ninja-build python3-pip
    - pip install --upgrade pip
    - pip3 install --user meson

language: C
compiler: gcc
script:
    - meson build
    - cd build
    - meson configure -Dwm=i3wm
    - ninja
