os: linux
dist: trusty

language: python

python: 3.6

matrix:
  include:
    - env: CC=gcc

before_install: 
    - sudo apt-get install -y build-essential 
    - sudo apt-get install -y gperf
 
install:
  - wget $(curl -s https://api.github.com/repos/ninja-build/ninja/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep ninja-linux.zip)
  - unzip -q ninja-linux.zip -d build
  - export PATH="$PWD/build:$PATH"
  - pip install meson

script:
    - meson build
    - cd build
    - meson configure -Dwm=i3wm
    - ninja
